version: '3'
services:
  file-server:
    image: file-server
    volumes:
      - ./host:/files/host
      - vol-host:/files/vol-host
    ports:
      - 8000:8000
volumes:
  vol-host:
      driver: local